package com.teckinfo.firstapplication;

//fields: emp id,first name(not null),last name(not null,job title(not null,email(not null,age(not null,
// salary(not null,createdby,createdon(time),
//updatedon(time),updatedby,created source,updated source,

import jakarta.persistence.*;

import javax.annotation.processing.Generated;
import java.util.Date;
import java.util.Random;

@Entity
@Table(name="Employee_Info")
@Generated("The Employee is generated by Nandhan")
public class Employee {
    @Id
    @Column(name="employee_id")
    private String employeeId;
    @Column(name = "first_name" ,length =50 , nullable = false)
    private String firstName;
    @Column(name = "last_name" ,length =50 , nullable = false)
    private String lastName;
    @Column(name = "job_title" ,length =50 , nullable = false)
    private String jobTitle;
    @Column(name = "email" ,length =100 , unique = true)
    private String email;
    @Column(name = "age" ,length =3 )
    private int age;
    @Column(name = "salary" ,length =10 )
    private double salary;
    @Column(name = "created_by" ,length =50 )
    private String createdBy;
    @Column(name = "created_on" ,length =50 )
    private Date createdOn;
    @Column(name = "updated_on" ,length =50 )
    private Date  updatedOn;
    @Column(name = "updated_by" ,length =50 )
    private String updatedBy;
    @Column(name = "created_source" ,length =50 )
    private String createdSource;
    @Column(name = "updated_source" ,length =50 )
    private String updatedSource;

//    public Employee(int employeeId, String firstName, String lastName, String jobTitle,
//                    String email, int age, double salary, String createdBy, Date createdOn,
//                    Date updatedOn, String updatedBy, String createdSource, String updatedSource) {
//        this.employeeId = employeeId;
//        this.firstName = firstName;
//        this.lastName = lastName;
//        this.jobTitle = jobTitle;
//        this.email = email;
//        this.age = age;
//        this.salary = salary;
//        this.createdBy = createdBy;
//        this.createdOn = createdOn;
//        this.updatedOn = updatedOn;
//        this.updatedBy = updatedBy;
//        this.createdSource = createdSource;
//        this.updatedSource = updatedSource;
//    }

    public String getEmployeeId() {
        return employeeId;
    }

    public Employee(){
        this.employeeId=generateRandomId();
    }

    private String generateRandomId() {
        Random random = new Random();
        int randomNumber = random.nextInt(90000) + 1000;
        return "Emp" + randomNumber;
    }
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getJobTitle() {
        return jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public double getSalary() {
        return salary;
    }

    public void setSalary(double salary) {
        this.salary = salary;
    }

    public String getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedOn() {
        return createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    public Date getUpdatedOn(Date date) {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public String getUpdatedBy(String s) {
        return updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public String getCreatedSource() {
        return createdSource;
    }

    public void setCreatedSource(String createdSource) {
        this.createdSource = createdSource;
    }

    public String getUpdatedSource(String updateEmployee) {
        return updatedSource;
    }

    public void setUpdatedSource(String updatedSource) {
        this.updatedSource = updatedSource;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "employeeId=" + employeeId +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", jobTitle='" + jobTitle + '\'' +
                ", email='" + email + '\'' +
                ", age=" + age +
                ", salary=" + salary +
                ", createdBy='" + createdBy + '\'' +
                ", createdOn=" + createdOn +
                ", updatedOn=" + updatedOn +
                ", updatedBy='" + updatedBy + '\'' +
                ", createdSource='" + createdSource + '\'' +
                ", updatedSource='" + updatedSource + '\'' +
                '}';
    }
}
